language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - 'pypy'
  - 'pypy3'
install:
  - pip install .
script: make test
notifications:
  flowdock:
    secure: "LbWkeeOXc8HkNe11/aGOgbwokxjk8c35FmjUZHU8YkETmlbiHup22fXgIXslhPhaN41xXhuiPnslVI7ZoBzyc17llHwIHCRQyqKFRg2Gb/nIcJ3QW7T+IsT98xhnoIUTFNnam4yNTd3HrpZD9dtr2EHsToAXZo5mayOCEU8UJig="
...